name: ci-build-release

on:
  push:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.version.outputs.version_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
      - run: flutter --version

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.0.2

      - name: Init keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          pwd
          echo $KEYSTORE_BASE64 | base64 -di > android/app/key.jks
          echo storePassword=$STORE_PASSWORD >> android/key.properties
          echo keyPassword=$KEY_PASSWORD >> android/key.properties
          echo keyAlias=$KEY_ALIAS >> android/key.properties
          echo storeFile=key.jks >> android/key.properties
          ls -1 ./android/key.*

      - name: Prepare to build
        run: |
          chmod +x ./android/gradlew
          chmod +x ./android/changelog/gitlog.sh
          flutter pub get

      - name: Build release
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: android
          arguments:
            assembleDebug assembleRelease

      - id: version
        name: Set version name
        run: |
          tag=`ls build/app/outputs/apk/release/*.apk | sed s/^[a-z/-]*//g | sed s/.apk//`
          echo tag=$tag
          echo version_name=$tag > $GITHUB_OUTPUT
          echo TAG=$tag >> $GITHUB_OUTPUT
          cp build/app/outputs/apk/debug/*.apk build/
          cp build/app/outputs/apk/release/*.apk build/
          java android/changelog/Changelog.java
          cp android/changelog/CHANGELOG.md build/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.version.outputs.TAG }}-outputs
          path: |
            build/*.apk
            build/*.md

  #      - name: Upload by webdav
  #        uses: bxb100/action-upload-webdav@v1
  #        with:
  #          webdav_address: ${{secrets.webdav_address}}
  #          webdav_username: ${{secrets.webdav_username}}
  #          webdav_password: ${{secrets.webdav_password}}
  #          webdav_upload_path: "/fime"
  #          files: build/app/outputs/apk/release/*.apk

  release:
    needs: build
    if: needs.build.outputs.version_name
    env:
      version_name: ${{ needs.build.outputs.version_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.version_name }}-outputs
      - run: |
          ls -R

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.version_name }}
          artifacts: ./*.apk
          body: ${{ env.version_name }} released.
          bodyFile: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
